"""Static reference data: hardware-type field templates and spec layouts."""

# ── Hardware type templates ───────────────────────────────────────────────────
HARDWARE_TEMPLATES = {
    "Hard Drive": [
        {"key": "Interface",   "type": "select",
         "options": ["MFM", "RLL", "ESDI", "SCSI", "PATA/IDE", "SATA", "USB"]},
        {"key": "Capacity",    "type": "number+unit", "units": ["MB", "GB", "TB"]},
        {"key": "RPM",         "type": "select",
         "options": ["3600", "4500", "5400", "7200", "10000", "15000", "Solid State"]},
        {"key": "Form factor", "type": "select",
         "options": ["5.25\" Full Height", "5.25\" Half Height", "3.5\"", "2.5\"", "1.8\"", "M.2"]},
        {"key": "Brand",       "type": "text"},
        {"key": "Model",       "type": "text"},
    ],
    "Videocard": [
        {"key": "Interface",   "type": "select",
         "options": ["ISA 8-bit", "ISA 16-bit", "MCA", "EISA", "VL-Bus",
                     "PCI", "AGP 1x", "AGP 2x", "AGP 4x", "AGP 8x", "PCIe x16"]},
        {"key": "VRAM",        "type": "number+unit", "units": ["KB", "MB", "GB"]},
        {"key": "VRAM Type",   "type": "select",
         "options": ["DRAM", "VRAM", "SGRAM", "EDO DRAM", "SDRAM",
                     "DDR", "DDR2", "GDDR3", "GDDR4", "GDDR5", "GDDR6"]},
        {"key": "Chipset",     "type": "text"},
        {"key": "Brand",       "type": "text"},
        {"key": "Output",      "type": "text"},
    ],
    "Memory": [
        {"key": "Type",        "type": "select",
         "options": ["DRAM", "FPM", "EDO", "BEDO", "SDRAM", "RDRAM",
                     "DDR", "DDR2", "DDR3", "DDR4", "DDR5"]},
        {"key": "Capacity",    "type": "number+unit", "units": ["KB", "MB", "GB"]},
        {"key": "Speed",       "type": "text"},
        {"key": "Form factor", "type": "select",
         "options": ["DIP chips", "SIMM 30-pin", "SIMM 72-pin", "DIMM 168-pin",
                     "SO-DIMM", "RIMM", "DIMM 184-pin", "DIMM 240-pin", "DIMM 288-pin"]},
        {"key": "Brand",       "type": "text"},
    ],
    "Soundcard": [
        {"key": "Interface",   "type": "select",
         "options": ["ISA 8-bit", "ISA 16-bit", "MCA", "EISA", "PCI", "PCIe", "USB", "Onboard"]},
        {"key": "Chipset",     "type": "text"},
        {"key": "Brand",       "type": "text"},
        {"key": "Model",       "type": "text"},
    ],
    "Processor": [
        {"key": "Brand",       "type": "select",
         "options": ["Intel", "AMD", "Cyrix", "IDT WinChip", "VIA", "NEC", "IBM", "Motorola", "Other"]},
        {"key": "Model",       "type": "text"},
        {"key": "Socket",      "type": "text"},
        {"key": "Speed",       "type": "text"},
        {"key": "Bus speed",   "type": "text"},
        {"key": "FPU",         "type": "select",
         "options": ["Built-in", "External (287)", "External (387)", "None"]},
    ],
    "Network card": [
        {"key": "Interface",   "type": "select",
         "options": ["ISA 8-bit", "ISA 16-bit", "MCA", "EISA", "PCI", "PCIe", "USB", "PCMCIA"]},
        {"key": "Speed",       "type": "select",
         "options": ["10 Mbps (10BASE-T)", "10 Mbps (10BASE-2 BNC)", "100 Mbps", "1 Gbps", "10 Gbps"]},
        {"key": "Connector",   "type": "select",
         "options": ["BNC (coax)", "RJ-45", "AUI", "BNC + RJ-45"]},
        {"key": "Brand",       "type": "text"},
        {"key": "Model",       "type": "text"},
    ],
    "Controller card": [
        {"key": "Type",        "type": "select",
         "options": ["IDE/PATA", "SCSI", "Floppy", "Multi-IO", "USB",
                     "FireWire", "RAID", "Serial/Parallel"]},
        {"key": "Interface",   "type": "select",
         "options": ["ISA 8-bit", "ISA 16-bit", "MCA", "EISA", "VL-Bus", "PCI", "PCIe"]},
        {"key": "Brand",       "type": "text"},
        {"key": "Model",       "type": "text"},
    ],
    "Floppy Drive": [
        {"key": "Size",        "type": "select",  "options": ["8\"", "5.25\"", "3.5\""]},
        {"key": "Capacity",    "type": "select",
         "options": ["160 KB", "180 KB", "320 KB", "360 KB",
                     "720 KB", "1.2 MB", "1.44 MB", "2.88 MB"]},
        {"key": "Interface",   "type": "select",
         "options": ["Standard floppy cable", "USB"]},
        {"key": "Brand",       "type": "text"},
    ],
    "Optical Drive": [
        {"key": "Type",        "type": "select",
         "options": ["CD-ROM", "CD-R", "CD-RW", "DVD-ROM", "DVD-R",
                     "DVD-RW", "DVD±RW", "BD-ROM", "BD-R", "BD-RE"]},
        {"key": "Interface",   "type": "select",
         "options": ["PATA/IDE", "SATA", "SCSI", "USB", "PCMCIA", "FireWire"]},
        {"key": "Read speed",  "type": "text"},
        {"key": "Write speed", "type": "text"},
        {"key": "Brand",       "type": "text"},
    ],
    "Peripheral": [
        {"key": "Type",      "type": "select",
         "options": ["Keyboard", "Mouse", "Joystick", "Trackball",
                     "Gamepad", "Lightpen", "Touchpad", "Other"]},
        {"key": "Interface", "type": "select",
         "options": ["AT (DIN-5)", "PS/2", "Serial (DB-9)", "USB",
                     "Wireless", "Proprietary", "Bus"]},
        {"key": "Brand",     "type": "text"},
        {"key": "Model",     "type": "text"},
    ],
    "Monitor": [
        {"key": "Size",          "type": "text"},
        {"key": "Type",          "type": "select",
         "options": ["CRT", "LCD", "Plasma", "EL (Electroluminescent)", "LED"]},
        {"key": "Resolution",    "type": "text"},
        {"key": "Refresh rate",  "type": "text"},
        {"key": "Interface",     "type": "select",
         "options": ["Composite", "MDA", "CGA", "EGA", "Hercules",
                     "VGA (DE-15)", "BNC", "DVI", "HDMI", "DisplayPort"]},
        {"key": "Brand",         "type": "text"},
        {"key": "Model",         "type": "text"},
    ],
}

DESKTOP_SPECS = [
    "Processor", "Memory", "Hard drive", "Videocard", "Soundcard",
    "Controller card", "IO Controller card", "Network card",
    "Optical drive", "Floppy drive", "Diskette drive",
    "Keyboard", "Mouse", "Monitor",
    "Operating System",
]

LAPTOP_SPECS = [
    "Processor", "Memory", "Hard drive", "Videocard", "Soundcard",
    "Network card", "Optical drive", "Floppy drive",
    "Screen", "Mouse/ Touchpad", "Battery", "Special ports",
    "Operating System",
]

# Maps Desktop spec labels → Hardware template type (Laptops use no map — all free text)
DESKTOP_SPEC_HW_MAP = {
    "Processor":          "Processor",
    "Hard drive":         "Hard Drive",
    "Videocard":          "Videocard",
    "Soundcard":          "Soundcard",
    "Controller card":    "Controller card",
    "IO Controller card": "Controller card",
    "Network card":       "Network card",
    "Optical drive":      "Optical Drive",
    "Floppy drive":       "Floppy Drive",
    "Diskette drive":     "Floppy Drive",
    "Keyboard":           "Peripheral",
    "Mouse":              "Peripheral",
    "Monitor":            "Monitor",
}
